promise
  .then((result) => {
    //body
  })
  .catch((error) => {
    //body
  });
